from typing import Protocol

from app.domain.types import Color


class RbcEngine(Protocol):
    def sense_actions(self) -> list[str]: ...
    def move_actions(self) -> list[str]: ...
    def sense(self, center: str) -> list[tuple[str, str | None, Color | None]]: ...
    def move(self, uci: str | None) -> tuple[str | None, str | None, str | None]: ...
    def is_over(self) -> bool: ...
